[theme]
primaryColor = "#0096fa"            # Bright Blue (main accent)
backgroundColor = "#f4f7fb"         # Light Gray-Blue (soft background)
secondaryBackgroundColor = "#ffffff" # White (cards/sidebar contrast)
textColor = "#1c1c1c"               # Almost Black (good readability)
font = "sans serif"
